---
- hosts: all
  become: yes
  tasks:
    - name: "Install puppet agent - Debian"
      include: "install-Debian.yml"
      when: ansible_os_family == 'Debian'
      tags: setup

    - name: "Install puppet agent - RedHat"
      include: "install-RedHat.yml"
      when: ansible_os_family == 'RedHat'
      tags: setup

    - name: "Install puppet module dependencies (puppetlabs-mysql)"
      shell: "/opt/puppetlabs/bin/puppet module install puppetlabs-mysql -v 6.1.0"
      args:
        creates: "/vagrant/modules/mysql"

    - name: "Install puppet module dependencies (puppetlabs-apt)"
      shell: "/opt/puppetlabs/bin/puppet module install puppetlabs-apt -v 6.0.0"
      args:
        creates: "/vagrant/modules/apt"
